services:
  fastapi:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fastapi-app-dev
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./README.md:/app/README.md
      - ./.env.development:/app/.env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
