services:
  fastapi:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
